version: "3"
services:
  #match-app:
  #  image: node:14.14.0-alpine3.12
  #  network_mode: "host"
  #  ports:
  #    - "3003:3003"
  #  working_dir: /home/node/app
  #  environment:
  #    - NODE_ENV=production
  #  volumes:
  #    - ../:/home/node/app
  #  expose:
  #    - "3003"
  #  command: "npm run build && npm run start"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.80.0/16
