version: '3'
services:
  mongo:
    image: mongo
    network_mode: 'host'
    ports:
      - '27017:27017'
    volumes:
      - '/mongo_users.js:/docker-entrypoint-initdb.d/001_users.js:ro'
      - './database_storage:/data/db'
