version: "3"
services:
  mongo:
    image: mongo
    network_mode: "host"
    ports:
      - "27017:27017"
    volumes:
      - "/mongo_users.js:/docker-entrypoint-initdb.d/001_users.js:ro"
      - "./database_storage:/data/db"

  zeebe:
    container_name: zeebe
    image: camunda/zeebe:0.24.2
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ./zeebe/lib/zeebe-hazelcast-exporter-0.9.1-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter-0.9.1-jar-with-dependencies.jar
      - ./zeebe/config/zeebe-broker-application.yaml:/usr/local/zeebe/config/application.yaml
      - ./zeebe/storage/zeebe_broker_data:/usr/local/zeebe/data
    networks:
      default:
        ipv4_address: 172.20.80.1

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      # sudo mkdir -p storage/elasticsearch_data; chmod 777 -R storage/elasticsearch_data
      - ./zeebe/storage/elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      default:
        ipv4_address: 172.20.80.2

  monitor:
    container_name: zeebe_monitor
    restart: always
    image: camunda/zeebe-simple-monitor:0.19.1
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      default:
        ipv4_address: 172.20.80.3

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.80.0/16
